name: dropwizard-continuous-integration

on:
  push:
    branch:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle build
        working-directory: .
        run: ./gradlew build -x test

      - name: Test using Gradle
        working-directory: .
        run: ./gradlew test

  system-test:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - uses: actions/checkout@v1

      - name: Run the server
        working-directory: .
        run: |
          chmod +x gradlew
          docker-compose up --build -d

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - run: pip install pytest requests

      - name: Run system tests
        working-directory: .
        run: pytest

      - name: Stop the server
        working-directory: .
        run: docker-compose down
